spring:
  application:
    name: NavUP Notification

  profiles:
    active: prod

notification:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761

server:
  port: 8090
